-- ============================================================
-- 02_place_order.sql — creates public.place_order(). SAFE TO RUN NOW.
--
-- Nothing calls this yet: it's only executable by service_role (the
-- future `place-order` Edge Function), and creating it changes no
-- existing table, function or grant. Run 01 first and check C1/C2/C6/
-- C8/C10/C11 against the ASSUMPTION lines below.
--
-- WHAT IT DOES — all in ONE transaction (a plpgsql function body always
-- runs inside the caller's transaction; any RAISE rolls back every write
-- below, including the slot reservation and the daily-counter bump):
--   1. validate inputs (cheap checks only — pricing is the Edge
--      Function's job; this function trusts p_items/p_total/
--      p_stamp_discount as already server-computed)
--   2. reserve the pickup slot       → public.reserve_pickup_slot()
--   3. assign short_id                → tester: random A123-style;
--                                      real: public.next_daily_order_number()
--   4. stored value: spend p_total    (inlined spend_stored_value() logic)
--      cash member: read balance      (for balance_snapshot)
--   5. insert the order               (status 'pending', printed false)
--   6. insert the stored-value 'deduction' transaction row
--   7. insert the stamp_redemptions row
--
-- ORDER OF OPERATIONS vs 04's foreign keys: rows that reference
-- orders(id) (steps 6 and 7) are inserted AFTER the order row (step 5),
-- so the FKs are satisfied immediately — no DEFERRABLE constraints
-- needed. The stored-value balance UPDATE (step 4) happens before the
-- order insert because it doesn't reference orders at all, and doing it
-- first lets balance_snapshot go into the single INSERT instead of a
-- follow-up UPDATE. Works the same before and after 04 runs (see the
-- note at step 6).
--
-- WHY IT CALLS reserve_pickup_slot()/next_daily_order_number() rather
-- than inlining them: identical behaviour by construction (see
-- 00_existing_functions.sql for their bodies). Both are called as the
-- function owner, so revoking anon EXECUTE on them at cutover (03)
-- doesn't affect this. Their row locks (pickup_slots row, today's
-- daily_order_counters row) are held until this transaction commits,
-- so concurrent place_order() calls serialise on the counter for the
-- few ms the rest of the function takes — and a rolled-back order
-- gives its number back instead of leaving a gap. Lock order is always
-- slot row → counter row → stored_value_accounts row, so two calls
-- can't deadlock on each other.
--
-- ERRORS — stable, machine-readable. Each is raised with a custom
-- SQLSTATE and the code as the message; supabase-js surfaces them as
-- error.code (SQLSTATE) and error.message (code). Map on error.code:
--   LB001  slot_full           the chosen slot has p_slot_cap orders already
--   LB002  already_redeemed    this member already redeemed this Taipei week
--   LB003  insufficient_funds  no stored-value account, or balance < p_total
--   LB004  not_friday          stamp redemption attempted on a non-Friday (Taipei)
--   LB005  order_number_failed next_daily_order_number() returned NULL
--   LB010  invalid_input       bad/inconsistent parameters (DETAIL says which)
-- Anything else (e.g. 23505 on the order's primary key if p_order_id is
-- reused) is an unexpected server error.
--
-- ASSUMPTION (C1): orders columns/types are as listed in 01's C1 header
--   — in particular stamp_discount integer, pickup_slot timestamptz,
--   member_name text, stamp_snapshot jsonb, balance_snapshot integer.
-- ASSUMPTION (C2): orders.payment_method check allows exactly
--   'cash_on_pickup' and 'stored_value' (README "Checkout payment
--   method"); stored_value_transactions.type allows 'deduction'.
-- ASSUMPTION (C2/C4): orders has no UNIQUE constraint/index on
--   short_id. (Real numbers repeat every day, so one can't exist
--   without a date column in it; if a unique index does exist, a tester
--   id collision would surface as a 23505 error.)
-- ASSUMPTION (C5): no triggers on orders / stamp_redemptions /
--   stored_value_* that would change these writes.
-- ASSUMPTION (C6): the tables are owned by the role that runs this file
--   (postgres) and don't FORCE row level security, so this security
--   definer function isn't blocked by the zero-policy tables.
-- ASSUMPTION (C9): live spend_stored_value() matches README (~line 265)
--   — step 4/6 below inline exactly that logic.
-- ============================================================

create or replace function public.place_order(
  p_order_id       uuid,        -- generated by the Edge Function; null = generate here
  p_user_id        text,        -- verified LINE sub; null = guest
  p_member_name    text,        -- member display name for the receipt; must be null for a guest
  p_is_test        boolean,     -- tester order (feature_flags); requires a member
  p_items          jsonb,       -- server-priced line items, stored as-is on orders.items
  p_total          integer,     -- server-computed total, AFTER any stamp discount
  p_note           text,
  p_pickup_slot    timestamptz, -- Edge Function validates grid/window/lead time
  p_payment_method text,        -- 'cash_on_pickup' | 'stored_value'
  p_redeem_stamp   boolean,     -- Edge Function has already checked the card is unlocked
  p_stamp_discount integer,     -- > 0 iff p_redeem_stamp
  p_stamp_snapshot jsonb,       -- receipt snapshot; members only
  p_slot_cap       integer      -- menu.json rules.pickup.perSlot
)
returns table (id uuid, short_id text, balance_after integer)
language plpgsql
security definer
set search_path = public
as $$
#variable_conflict use_column
declare
  v_order_id     uuid    := coalesce(p_order_id, gen_random_uuid());
  v_is_test      boolean := coalesce(p_is_test, false);
  v_redeem       boolean := coalesce(p_redeem_stamp, false);
  v_discount     integer := coalesce(p_stamp_discount, 0);
  v_short_id     text;
  v_order_number integer;
  v_balance      integer;          -- balance_snapshot / balance_after; null for guests
  v_taipei_today date;
  v_week_start   date;
  v_rows         integer;
begin
  -- ---- 1. validation (no writes yet) --------------------------------
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_items must be a non-empty JSON array';
  end if;
  if p_total is null or p_total < 0 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_total must be a non-negative integer';
  end if;
  if p_payment_method is null or p_payment_method not in ('cash_on_pickup', 'stored_value') then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_payment_method must be cash_on_pickup or stored_value';
  end if;
  if p_pickup_slot is null then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_pickup_slot is required';
  end if;
  if p_slot_cap is null or p_slot_cap < 1 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_slot_cap must be >= 1';
  end if;
  if p_user_id is null and (p_member_name is not null or p_stamp_snapshot is not null
                            or v_is_test or v_redeem or p_payment_method = 'stored_value') then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'guest orders cannot carry member_name, stamp_snapshot, is_test, a stamp redemption or stored-value payment';
  end if;
  if v_redeem and v_discount <= 0 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_stamp_discount must be > 0 when p_redeem_stamp';
  end if;
  if not v_redeem and v_discount <> 0 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_stamp_discount must be 0 unless p_redeem_stamp';
  end if;
  if p_payment_method = 'stored_value' and p_total <= 0 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'stored_value payment needs p_total > 0';
  end if;

  -- Taipei calendar date exactly as _shared/taipeiWeek.ts computes it:
  -- shift the UTC instant by a fixed +8h and read the date (no tz
  -- database). week_start = Monday on or before that date, i.e.
  -- taipeiWeekMonday()'s (dayOfWeek + 6) % 7 offset == isodow - 1.
  v_taipei_today := ((now() at time zone 'UTC') + interval '8 hours')::date;
  v_week_start   := v_taipei_today - (extract(isodow from v_taipei_today)::int - 1);

  -- Defence in depth: redeem-stamp-drink / the Edge Function already
  -- enforce Friday; this makes a stray call on another day fail loudly
  -- instead of burning the member's week.
  if v_redeem and extract(isodow from v_taipei_today) <> 5 then
    raise exception using errcode = 'LB004', message = 'not_friday';
  end if;

  -- ---- 2. reserve the pickup slot ------------------------------------
  -- Same function the live app calls. NULL = full (the conditional
  -- DO UPDATE matched no row). Rolled back with everything else if a
  -- later step fails, so a failed order never keeps a slot.
  if public.reserve_pickup_slot(p_pickup_slot, p_slot_cap) is null then
    raise exception using errcode = 'LB001', message = 'slot_full';
  end if;

  -- ---- 3. short_id ---------------------------------------------------
  if v_is_test then
    -- Tester orders keep the random letter + 3 digits scheme (e.g.
    -- "B482") — see makeTestShortId() in supabase-config.js. Never
    -- touches the daily counter.
    v_short_id := chr(65 + floor(random() * 26)::int) || (100 + floor(random() * 900)::int)::text;
  else
    v_order_number := public.next_daily_order_number();
    if v_order_number is null then
      -- Never fall back to a random id for a real order.
      raise exception using errcode = 'LB005', message = 'order_number_failed';
    end if;
    -- Zero-pad to 3 like JS padStart(3, "0"); lpad() alone would
    -- TRUNCATE a 4-digit number ("1000" -> "100"), so only pad short ones.
    v_short_id := case when length(v_order_number::text) < 3
                       then lpad(v_order_number::text, 3, '0')
                       else v_order_number::text end;
  end if;

  -- ---- 4. stored value spend / member balance read -------------------
  if p_payment_method = 'stored_value' then
    -- Same conditional UPDATE as spend_stored_value(): only succeeds if
    -- the account exists and covers the amount; the row lock it takes
    -- makes concurrent spends on one account queue up correctly.
    update stored_value_accounts
       set balance = balance - p_total, updated_at = now()
     where user_id = p_user_id and balance >= p_total
     returning balance into v_balance;
    if v_balance is null then
      raise exception using errcode = 'LB003', message = 'insufficient_funds';
    end if;
  elsif p_user_id is not null then
    -- Member paying cash: snapshot the current balance for the receipt
    -- (null if they've never topped up).
    select a.balance into v_balance
      from stored_value_accounts a
     where a.user_id = p_user_id;
  end if;

  -- ---- 5. the order --------------------------------------------------
  insert into orders (
    id, short_id, items, total, note, status, printed, user_id, is_test,
    payment_method, stamp_discount, pickup_slot, member_name,
    stamp_snapshot, balance_snapshot
  ) values (
    v_order_id, v_short_id, p_items, p_total, nullif(p_note, ''), 'pending', false, p_user_id, v_is_test,
    p_payment_method, v_discount, p_pickup_slot, p_member_name,
    p_stamp_snapshot, v_balance
  );

  -- ---- 6. stored value ledger row (references the order) -------------
  if p_payment_method = 'stored_value' then
    -- Before 04, order_id is text: uuid -> text is an assignment cast,
    -- so this insert works. After 04 it's uuid -> uuid. Same statement
    -- either way.
    insert into stored_value_transactions (user_id, amount, type, order_id)
    values (p_user_id, -p_total, 'deduction', v_order_id);
  end if;

  -- ---- 7. stamp redemption (references the order) --------------------
  if v_redeem then
    insert into stamp_redemptions (user_id, week_start, order_id)
    values (p_user_id, v_week_start, v_order_id)
    on conflict (user_id, week_start) do nothing;
    get diagnostics v_rows = row_count;
    if v_rows = 0 then
      -- (user_id, week_start) PK already taken — rolls back the order,
      -- the spend and the slot too.
      raise exception using errcode = 'LB002', message = 'already_redeemed';
    end if;
  end if;

  id            := v_order_id;
  short_id      := v_short_id;
  balance_after := v_balance;
  return next;
end;
$$;

-- Supabase's default privileges grant EXECUTE on new public functions to
-- anon and authenticated (and PostgreSQL grants it to PUBLIC), so all
-- three must be revoked explicitly. Only the Edge Function's
-- service-role client may call this.
revoke all on function public.place_order(uuid, text, text, boolean, jsonb, integer, text,
                                          timestamptz, text, boolean, integer, jsonb, integer)
  from public, anon, authenticated;
grant execute on function public.place_order(uuid, text, text, boolean, jsonb, integer, text,
                                             timestamptz, text, boolean, integer, jsonb, integer)
  to service_role;


-- ============================================================
-- OPTIONAL SMOKE TEST — commented out. Runs place_order() inside a
-- transaction and ROLLS BACK, so nothing persists: the order row, the
-- slot reservation and the counter bump are all undone. Pick a slot in
-- the future. Run the whole block at once (BEGIN ... ROLLBACK).
-- ============================================================
-- begin;
--   -- tester order: random short_id, no counter
--   select * from public.place_order(
--     null, 'smoke-test-user', '測試', true,
--     '[{"id":"sn-02","name":"脆薯","modifiers":"","qty":1,"subtotal":30}]'::jsonb, 30, null,
--     '2026-09-29 06:00:00+08', 'cash_on_pickup', false, 0, null, 6);
--   -- real guest order: next daily number, no balance
--   select * from public.place_order(
--     null, null, null, false,
--     '[{"id":"sn-02","name":"脆薯","modifiers":"","qty":1,"subtotal":30}]'::jsonb, 30, null,
--     '2026-09-29 06:00:00+08', 'cash_on_pickup', false, 0, null, 6);
--   -- expected error: guest paying stored value -> LB010 invalid_input
--   -- select * from public.place_order(null, null, null, false,
--   --   '[{"id":"sn-02"}]'::jsonb, 30, null, '2026-09-29 06:00:00+08',
--   --   'stored_value', false, 0, null, 6);
-- rollback;
