-- ============================================================
-- 06_place_order_idempotent.sql — idempotent retries for place_order().
--
-- RUN THIS WHOLE FILE IN ONE SQL-EDITOR RUN (create or replace + revoke
-- + grant together). CREATE OR REPLACE keeps the existing grants, but
-- the revoke/grant pair is repeated so the function can never be left
-- callable by anon/authenticated even briefly.
--
-- Identical to 02_place_order.sql except step 0 (marked NEW below):
-- if an order with p_order_id already exists for the SAME caller (same
-- p_user_id, or both null for a guest), return that order's
-- id / short_id / balance_snapshot and do nothing else. Same id for a
-- different caller → invalid_input (LB010). Same signature, same return
-- type, same error codes, so the deployed place-order keeps working
-- before and after this runs.
--
-- Why: the app now generates the order id when 送出訂單 is tapped and
-- REUSES it for any retry of that checkout (incl. after a network error
-- where the first request may actually have succeeded). place-order
-- also checks for an existing order before re-validating, and this is
-- the backstop for two identical requests racing each other.
--
-- ASSUMPTION (C2): orders.id is the primary key (so at most one row per
--   id). ASSUMPTION: hashtextextended() exists (PostgreSQL 11+; Supabase
--   is 15+).
-- ============================================================

create or replace function public.place_order(
  p_order_id       uuid,        -- generated by the Edge Function; null = generate here
  p_user_id        text,        -- verified LINE sub; null = guest
  p_member_name    text,        -- member display name for the receipt; must be null for a guest
  p_is_test        boolean,     -- tester order (feature_flags); requires a member
  p_items          jsonb,       -- server-priced line items, stored as-is on orders.items
  p_total          integer,     -- server-computed total, AFTER any stamp discount
  p_note           text,
  p_pickup_slot    timestamptz, -- Edge Function validates grid/window/lead time
  p_payment_method text,        -- 'cash_on_pickup' | 'stored_value'
  p_redeem_stamp   boolean,     -- Edge Function has already checked the card is unlocked
  p_stamp_discount integer,     -- > 0 iff p_redeem_stamp
  p_stamp_snapshot jsonb,       -- receipt snapshot; members only
  p_slot_cap       integer      -- menu.json rules.pickup.perSlot
)
returns table (id uuid, short_id text, balance_after integer)
language plpgsql
security definer
set search_path = public
as $$
#variable_conflict use_column
declare
  v_order_id     uuid    := coalesce(p_order_id, gen_random_uuid());
  v_is_test      boolean := coalesce(p_is_test, false);
  v_redeem       boolean := coalesce(p_redeem_stamp, false);
  v_discount     integer := coalesce(p_stamp_discount, 0);
  v_short_id     text;
  v_order_number integer;
  v_balance      integer;          -- balance_snapshot / balance_after; null for guests
  v_taipei_today date;
  v_week_start   date;
  v_rows         integer;
  v_existing     record;          -- idempotency: an order already saved under this id
begin
  -- ---- 0. idempotency (NEW in 06) ----------------------------------
  -- A retry of the same checkout sends the same id (the app generates it
  -- once per checkout). If that order already exists, return it and do
  -- NOTHING else — no slot, no order number, no stored-value spend, no
  -- stamp redemption — so a retry after a lost response can never
  -- double-charge or double-book.
  --
  -- The advisory lock serialises two requests for the same id arriving
  -- at the same moment: the second waits for the first to commit, then
  -- finds its row here. It's transaction-scoped (released at commit or
  -- rollback). hashtextextended() collisions would only make two
  -- unrelated orders wait for each other briefly — never wrong results.
  if p_order_id is not null then
    perform pg_advisory_xact_lock(hashtextextended(p_order_id::text, 0));

    select o.id, o.short_id, o.user_id, o.balance_snapshot
      into v_existing
      from orders o
     where o.id = p_order_id;

    if found then
      if v_existing.user_id is not distinct from p_user_id then
        id            := v_existing.id;
        short_id      := v_existing.short_id;
        balance_after := v_existing.balance_snapshot;
        return next;
        return;
      end if;
      -- Same id, different caller (or guest vs member): never reveal or
      -- touch someone else's order.
      raise exception using errcode = 'LB010', message = 'invalid_input',
        detail = 'p_order_id is already used by a different caller';
    end if;
  end if;
  -- ---- 1. validation (no writes yet) --------------------------------
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_items must be a non-empty JSON array';
  end if;
  if p_total is null or p_total < 0 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_total must be a non-negative integer';
  end if;
  if p_payment_method is null or p_payment_method not in ('cash_on_pickup', 'stored_value') then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_payment_method must be cash_on_pickup or stored_value';
  end if;
  if p_pickup_slot is null then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_pickup_slot is required';
  end if;
  if p_slot_cap is null or p_slot_cap < 1 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_slot_cap must be >= 1';
  end if;
  if p_user_id is null and (p_member_name is not null or p_stamp_snapshot is not null
                            or v_is_test or v_redeem or p_payment_method = 'stored_value') then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'guest orders cannot carry member_name, stamp_snapshot, is_test, a stamp redemption or stored-value payment';
  end if;
  if v_redeem and v_discount <= 0 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_stamp_discount must be > 0 when p_redeem_stamp';
  end if;
  if not v_redeem and v_discount <> 0 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'p_stamp_discount must be 0 unless p_redeem_stamp';
  end if;
  if p_payment_method = 'stored_value' and p_total <= 0 then
    raise exception using errcode = 'LB010', message = 'invalid_input',
      detail = 'stored_value payment needs p_total > 0';
  end if;

  -- Taipei calendar date exactly as _shared/taipeiWeek.ts computes it:
  -- shift the UTC instant by a fixed +8h and read the date (no tz
  -- database). week_start = Monday on or before that date, i.e.
  -- taipeiWeekMonday()'s (dayOfWeek + 6) % 7 offset == isodow - 1.
  v_taipei_today := ((now() at time zone 'UTC') + interval '8 hours')::date;
  v_week_start   := v_taipei_today - (extract(isodow from v_taipei_today)::int - 1);

  -- Defence in depth: redeem-stamp-drink / the Edge Function already
  -- enforce Friday; this makes a stray call on another day fail loudly
  -- instead of burning the member's week.
  if v_redeem and extract(isodow from v_taipei_today) <> 5 then
    raise exception using errcode = 'LB004', message = 'not_friday';
  end if;

  -- ---- 2. reserve the pickup slot ------------------------------------
  -- Same function the live app calls. NULL = full (the conditional
  -- DO UPDATE matched no row). Rolled back with everything else if a
  -- later step fails, so a failed order never keeps a slot.
  if public.reserve_pickup_slot(p_pickup_slot, p_slot_cap) is null then
    raise exception using errcode = 'LB001', message = 'slot_full';
  end if;

  -- ---- 3. short_id ---------------------------------------------------
  if v_is_test then
    -- Tester orders keep the random letter + 3 digits scheme (e.g.
    -- "B482") — see makeTestShortId() in supabase-config.js. Never
    -- touches the daily counter.
    v_short_id := chr(65 + floor(random() * 26)::int) || (100 + floor(random() * 900)::int)::text;
  else
    v_order_number := public.next_daily_order_number();
    if v_order_number is null then
      -- Never fall back to a random id for a real order.
      raise exception using errcode = 'LB005', message = 'order_number_failed';
    end if;
    -- Zero-pad to 3 like JS padStart(3, "0"); lpad() alone would
    -- TRUNCATE a 4-digit number ("1000" -> "100"), so only pad short ones.
    v_short_id := case when length(v_order_number::text) < 3
                       then lpad(v_order_number::text, 3, '0')
                       else v_order_number::text end;
  end if;

  -- ---- 4. stored value spend / member balance read -------------------
  if p_payment_method = 'stored_value' then
    -- Same conditional UPDATE as spend_stored_value(): only succeeds if
    -- the account exists and covers the amount; the row lock it takes
    -- makes concurrent spends on one account queue up correctly.
    update stored_value_accounts
       set balance = balance - p_total, updated_at = now()
     where user_id = p_user_id and balance >= p_total
     returning balance into v_balance;
    if v_balance is null then
      raise exception using errcode = 'LB003', message = 'insufficient_funds';
    end if;
  elsif p_user_id is not null then
    -- Member paying cash: snapshot the current balance for the receipt
    -- (null if they've never topped up).
    select a.balance into v_balance
      from stored_value_accounts a
     where a.user_id = p_user_id;
  end if;

  -- ---- 5. the order --------------------------------------------------
  insert into orders (
    id, short_id, items, total, note, status, printed, user_id, is_test,
    payment_method, stamp_discount, pickup_slot, member_name,
    stamp_snapshot, balance_snapshot
  ) values (
    v_order_id, v_short_id, p_items, p_total, nullif(p_note, ''), 'pending', false, p_user_id, v_is_test,
    p_payment_method, v_discount, p_pickup_slot, p_member_name,
    p_stamp_snapshot, v_balance
  );

  -- ---- 6. stored value ledger row (references the order) -------------
  if p_payment_method = 'stored_value' then
    -- Before 04, order_id is text: uuid -> text is an assignment cast,
    -- so this insert works. After 04 it's uuid -> uuid. Same statement
    -- either way.
    insert into stored_value_transactions (user_id, amount, type, order_id)
    values (p_user_id, -p_total, 'deduction', v_order_id);
  end if;

  -- ---- 7. stamp redemption (references the order) --------------------
  if v_redeem then
    insert into stamp_redemptions (user_id, week_start, order_id)
    values (p_user_id, v_week_start, v_order_id)
    on conflict (user_id, week_start) do nothing;
    get diagnostics v_rows = row_count;
    if v_rows = 0 then
      -- (user_id, week_start) PK already taken — rolls back the order,
      -- the spend and the slot too.
      raise exception using errcode = 'LB002', message = 'already_redeemed';
    end if;
  end if;

  id            := v_order_id;
  short_id      := v_short_id;
  balance_after := v_balance;
  return next;
end;
$$;

-- Supabase's default privileges grant EXECUTE on new public functions to
-- anon and authenticated (and PostgreSQL grants it to PUBLIC), so all
-- three must be revoked explicitly. Only the Edge Function's
-- service-role client may call this.
revoke all on function public.place_order(uuid, text, text, boolean, jsonb, integer, text,
                                          timestamptz, text, boolean, integer, jsonb, integer)
  from public, anon, authenticated;
grant execute on function public.place_order(uuid, text, text, boolean, jsonb, integer, text,
                                             timestamptz, text, boolean, integer, jsonb, integer)
  to service_role;

-- ============================================================
-- OPTIONAL SMOKE TEST — commented out. Everything inside BEGIN…ROLLBACK
-- is undone (orders, slot bookings, the order counter, the test member
-- and its stored-value account). Use a slot in the future. Run the whole
-- block at once. Expected results are noted on each select.
-- ============================================================
-- begin;
--   -- a throwaway member with NT$500 of stored value
--   insert into members (user_id, display_name) values ('idem-test-user', 'idem test');
--   insert into stored_value_accounts (user_id, balance) values ('idem-test-user', 500);
--
--   -- 1st call: new order, pays 60 from stored value -> balance_after 440
--   select * from public.place_order(
--     '11111111-2222-3333-4444-555555555555', 'idem-test-user', 'idem test', false,
--     '[{"id":"sn-02","name":"脆薯","modifiers":"","qty":2,"subtotal":60}]'::jsonb, 60, null,
--     '2026-09-30 06:00:00+08', 'stored_value', false, 0, null, 6);
--   -- 2nd call, SAME id + same user: same id and short_id, balance_after 440 again
--   select * from public.place_order(
--     '11111111-2222-3333-4444-555555555555', 'idem-test-user', 'idem test', false,
--     '[{"id":"sn-02","name":"脆薯","modifiers":"","qty":2,"subtotal":60}]'::jsonb, 60, null,
--     '2026-09-30 06:00:00+08', 'stored_value', false, 0, null, 6);
--   -- charged once: expect balance 440 and exactly ONE deduction row
--   select balance from stored_value_accounts where user_id = 'idem-test-user';
--   select count(*) as deductions from stored_value_transactions where user_id = 'idem-test-user' and type = 'deduction';
--   -- one order, one slot booking (taken = 1 unless the slot already had orders)
--   select count(*) as orders_with_this_id from orders where id = '11111111-2222-3333-4444-555555555555';
--   select slot, taken from pickup_slots where slot = '2026-09-30 06:00:00+08';
-- rollback;
--
-- Different caller with the same id -> ERROR LB010 invalid_input
-- ("p_order_id is already used by a different caller"). Run separately:
-- begin;
--   insert into members (user_id, display_name) values ('idem-test-user', 'idem test');
--   select * from public.place_order(
--     '11111111-2222-3333-4444-555555555555', 'idem-test-user', 'idem test', false,
--     '[{"id":"sn-02","name":"脆薯","modifiers":"","qty":1,"subtotal":30}]'::jsonb, 30, null,
--     '2026-09-30 06:00:00+08', 'cash_on_pickup', false, 0, null, 6);
--   select * from public.place_order(
--     '11111111-2222-3333-4444-555555555555', null, null, false,
--     '[{"id":"sn-02","name":"脆薯","modifiers":"","qty":1,"subtotal":30}]'::jsonb, 30, null,
--     '2026-09-30 06:00:00+08', 'cash_on_pickup', false, 0, null, 6);
-- rollback;
